In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# load the Dataset
df = pd.read_csv('data_set_for_overfitting.csv')

In [4]:
#EDA -> Exploaitry data Analysis
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 51 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      20 non-null     float64
 1   X2      20 non-null     float64
 2   X3      20 non-null     float64
 3   X4      20 non-null     float64
 4   X5      20 non-null     float64
 5   X6      20 non-null     float64
 6   X7      20 non-null     float64
 7   X8      20 non-null     float64
 8   X9      20 non-null     float64
 9   X10     20 non-null     float64
 10  X11     20 non-null     float64
 11  X12     20 non-null     float64
 12  X13     20 non-null     float64
 13  X14     20 non-null     float64
 14  X15     20 non-null     float64
 15  X16     20 non-null     float64
 16  X17     20 non-null     float64
 17  X18     20 non-null     float64
 18  X19     20 non-null     float64
 19  X20     20 non-null     float64
 20  X21     20 non-null     float64
 21  X22     20 non-null     float64
 22  X23     20 non-null     float64
 23  X24     20 non-null     float64
 24  X25     20 non-null     float64
 25  X26     20 non-null     float64
 26  X27     20 non-null     float64
 27  X28     20 non-null     float64
 28  X29     20 non-null     float64
 29  X30     20 non-null     float64
 30  X31     20 non-null     float64
 31  X32     20 non-null     float64
 32  X33     20 non-null     float64
 33  X34     20 non-null     float64
 34  X35     20 non-null     float64
 35  X36     20 non-null     float64
 36  X37     20 non-null     float64
 37  X38     20 non-null     float64
 38  X39     20 non-null     float64
 39  X40     20 non-null     float64
 40  X41     20 non-null     float64
 41  X42     20 non-null     float64
 42  X43     20 non-null     float64
 43  X44     20 non-null     float64
 44  X45     20 non-null     float64
 45  X46     20 non-null     float64
 46  X47     20 non-null     float64
 47  X48     20 non-null     float64
 48  X49     20 non-null     float64
 49  X50     20 non-null     float64
 50  y       20 non-null     float64
dtypes: float64(51)
memory usage: 8.1 KB

In [5]:
df.describe()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X42,X43,X44,X45,X46,X47,X48,X49,X50,y
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,...,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.00000,20.000000
mean,1.484000,1.734000,1.589000,1.378000,1.889500,1.422500,1.572500,1.700000,1.422500,1.460500,...,1.654500,1.377500,1.783000,1.449000,1.517000,1.827000,1.322500,1.627000,1.69400,17.899500
std,0.895729,0.821779,0.909719,0.846551,0.821997,0.858161,1.004091,0.924127,0.833944,0.930328,...,0.932622,0.973322,0.818015,0.821884,0.874379,0.841528,0.819819,0.953802,0.94234,6.875941
min,0.220000,0.440000,0.330000,0.330000,0.440000,0.220000,0.220000,0.330000,0.330000,0.330000,...,0.330000,0.220000,0.440000,0.440000,0.440000,0.440000,0.220000,0.220000,0.33000,8.230000
25%,0.742500,1.135000,0.660000,0.660000,1.227500,0.607500,0.770000,1.135000,0.742500,0.742500,...,0.550000,0.550000,1.302500,0.852500,0.715000,1.357500,0.715000,0.770000,0.85250,12.117500
50%,1.385000,1.825000,1.550000,1.275000,1.995000,1.495000,1.495000,1.550000,1.330000,1.165000,...,1.770000,1.105000,1.715000,1.330000,1.385000,1.825000,1.220000,1.550000,1.44000,17.060000
75%,2.365000,2.357500,2.392500,2.165000,2.577500,1.907500,2.577500,2.660000,2.020000,2.110000,...,2.577500,2.467500,2.577500,1.715000,2.330000,2.412500,1.742500,2.577500,2.60500,23.060000
max,2.880000,2.990000,2.990000,2.880000,2.880000,2.880000,2.990000,2.990000,2.990000,2.990000,...,2.990000,2.880000,2.880000,2.990000,2.880000,2.990000,2.990000,2.990000,2.99000,31.230000

In [56]:
corr_with_target = df.corr()['y'].sort_values(ascending=False)
print(corr_with_target)

y      1.000000
X37    0.488572
X28    0.452755
X40    0.449180
X34    0.443386
X10    0.440333
X49    0.434115
X22    0.420302
X43    0.413832
X7     0.401527
X13    0.398506
X25    0.380938
X46    0.379524
X16    0.347675
X19    0.339836
X31    0.338968
X4     0.261422
X1     0.189994
X30   -0.049966
X3    -0.062274
X5    -0.068894
X39   -0.084132
X33   -0.093307
X15   -0.099228
X20   -0.114637
X48   -0.127220
X45   -0.131652
X12   -0.156396
X9    -0.165457
X18   -0.175232
X27   -0.185271
X36   -0.194003
X2    -0.197278
X32   -0.204557
X21   -0.212093
X23   -0.214490
X14   -0.223707
X24   -0.225863
X42   -0.227953
X47   -0.265908
X6    -0.290456
X11   -0.293208
X41   -0.294382
X8    -0.296333
X50   -0.310659
X38   -0.312940
X17   -0.326536
X26   -0.339664
X35   -0.340135
X44   -0.340543
X29   -0.349457
Name: y, dtype: float64

In [7]:
x = df.drop('y',axis=1)
y = df['y']

In [26]:


#Spliting the Dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,random_state=42)

In [27]:
from sklearn.linear_model import LinearRegression
def create_Linear_regression_model():
    model = LinearRegression()
    model.fit(x_train,y_train)
    return model

In [64]:
from sklearn.linear_model import Lasso
def create_Lasso_model():
    model=Lasso(alpha=5)
    model.fit(x_train,y_train)
    return model

In [65]:
from sklearn.linear_model import Ridge
def create_Ridge_model():
    model=Ridge(alpha=5)
    model.fit(x_train,y_train)
    return model

In [66]:
from sklearn.linear_model import ElasticNet
def create_Elastic_Net():
    model=ElasticNet(alpha=5)
    model.fit(x_train,y_train)
    return model

In [67]:
linear_regression_model = create_Linear_regression_model()
lasso_regression_model = create_Lasso_model()
ridge_regression_model = create_Ridge_model()
elasticnet_regression_model = create_Elastic_Net()
models=[
    {"model_name":"Linear Model","model":linear_regression_model},
    {"model_name":"Lasso Model","model":lasso_regression_model},
    {"model_name":"Ridge Model","model":ridge_regression_model},
    {"model_name":"Elastic Net Model","model":ridge_regression_model}
]

In [68]:
##Evaluation of model
from sklearn.metrics import mean_absolute_error,mean_squared_error,mean_absolute_percentage_error,root_mean_squared_error,r2_score
def evaluation_of_metrices(model,model_name,x,y):
    y_pred = model.predict(x)
    mae = mean_absolute_error(y,y_pred)
    mse = mean_squared_error(y,y_pred)
    mape = mean_absolute_percentage_error(y,y_pred)
    rmse = root_mean_squared_error(y,y_pred)
    r2 = r2_score(y,y_pred)
    return mae,mse,mape,rmse,r2

In [69]:
#For the Training Data
elvaluation_for_training=[]
#evaluate every model
for model_info in models:
    metrice = evaluation_of_metrices(model=model_info["model"],model_name=["model_name"],x=x_train,y=y_train)
    elvaluation_for_training.append(metrice)

pd.DataFrame(elvaluation_for_training,columns=["MAE","MSE","MAPE","RMSE","R2"])

            MAE           MSE          MAPE          RMSE        R2
0  2.207758e-14  6.026897e-28  1.341587e-15  2.454974e-14  1.000000
1  6.630204e+00  5.679660e+01  4.431755e-01  7.536352e+00  0.000000
2  4.329262e+00  2.374980e+01  2.886321e-01  4.873377e+00  0.581845
3  4.329262e+00  2.374980e+01  2.886321e-01  4.873377e+00  0.581845

In [70]:
#For Testing Data
elvaluation_for_training=[]
#evaluate every model
for model_info in models:
    metrice = evaluation_of_metrices(model=model_info["model"],model_name=["model_name"],x=x_test,y=y_test)
    elvaluation_for_training.append(metrice)

pd.DataFrame(elvaluation_for_training,columns=["MAE","MSE","MAPE","RMSE","R2"])

        MAE        MSE      MAPE      RMSE        R2
0  9.108189  93.943784  0.542876  9.692460 -4.616023
1  3.543095  17.388164  0.209555  4.169912 -0.039476
2  3.992502  22.823660  0.216212  4.777411 -0.364414
3  3.992502  22.823660  0.216212  4.777411 -0.364414