### Import required Packages

### PS:
- predict the customers segment based on wine customer purchses

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv('Wine.csv')
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1

### EDA

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Alcohol               178 non-null    float64
 1   Malic_Acid            178 non-null    float64
 2   Ash                   178 non-null    float64
 3   Ash_Alcanity          178 non-null    float64
 4   Magnesium             178 non-null    int64
 5   Total_Phenols         178 non-null    float64
 6   Flavanoids            178 non-null    float64
 7   Nonflavanoid_Phenols  178 non-null    float64
 8   Proanthocyanins       178 non-null    float64
 9   Color_Intensity       178 non-null    float64
 10  Hue                   178 non-null    float64
 11  OD280                 178 non-null    float64
 12  Proline               178 non-null    int64
 13  Customer_Segment      178 non-null    int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB

In [9]:
df.describe()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,1.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,1.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,1.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,2.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,3.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,3.000000

In [10]:
df.corr()['Customer_Segment'].abs().sort_values()

Ash                     0.049643
Magnesium               0.209179
Color_Intensity         0.265668
Alcohol                 0.328222
Malic_Acid              0.437776
Nonflavanoid_Phenols    0.489109
Proanthocyanins         0.499130
Ash_Alcanity            0.517859
Hue                     0.617369
Proline                 0.633717
Total_Phenols           0.719163
OD280                   0.788230
Flavanoids              0.847498
Customer_Segment        1.000000
Name: Customer_Segment, dtype: float64

In [11]:
df.drop(['Ash','Magnesium','Color_Intensity'],axis=1,inplace=True)

In [12]:
df['Customer_Segment'].value_counts()

Customer_Segment
2    71
1    59
3    48
Name: count, dtype: int64

### Data Prepration

In [13]:
# Split the data
x = df.drop('Customer_Segment',axis=1)
y = df['Customer_Segment']

In [25]:
# change the classes 
# 0->1 1->2 2->3
y=y-1

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,random_state=42)

### Build the MOdels

In [27]:
from sklearn.ensemble import AdaBoostClassifier
def create_adaboost_model():
    model = AdaBoostClassifier()
    model.fit(x_train,y_train)
    return model

In [28]:
from sklearn.ensemble import GradientBoostingClassifier
def create_gradient_model():
    model = GradientBoostingClassifier(learning_rate=0.1,max_depth=4,n_estimators=10,verbose=1)
    model.fit(x_train,y_train)
    return model

In [29]:
from xgboost import XGBClassifier
def create_XGB_model():
    model=XGBClassifier()
    model.fit(x_train,y_train)
    return model

In [30]:
from lightgbm import LGBMClassifier
def create_lgbm_model():
    model = LGBMClassifier(learning_rate=0.1,n_estimators=10)
    model.fit(x_train,y_train)
    return model

In [31]:
from catboost import CatBoostClassifier
def create_catboot_model():
    model = CatBoostClassifier()
    model.fit(x_train,y_train)
    return model

### Evaluate Model

In [36]:
from sklearn.metrics import accuracy_score,precision_score,f1_score,recall_score
def evaluate_model(model,name,x,y_true):
    y_pred = model.predict(x)
    accuracy = accuracy_score(y_true,y_pred)
    precision = precision_score(y_true,y_pred,average='micro')
    f1 = f1_score(y_true,y_pred,average='micro')
    recall = recall_score(y_true,y_pred,average='micro')
    return name,accuracy,precision,f1,recall

In [37]:
#create all models
model_adaboost =  create_adaboost_model()
model_gredient_boost = create_gradient_model()
model_xgb = create_XGB_model()
model_light_gbm = create_lgbm_model()
model_cat_boost = create_catboot_model()

      Iter       Train Loss   Remaining Time
         1           0.8963            0.17s
         2           0.7535            0.13s
         3           0.6395            0.12s
         4           0.5437            0.10s
         5           0.4646            0.07s
         6           0.3985            0.05s
         7           0.3430            0.04s
         8           0.2959            0.03s
         9           0.2558            0.01s
        10           0.2216            0.00s
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000069 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 353
[LightGBM] [Info] Number of data points in the train set: 124, number of used features: 10
[LightGBM] [Info] Start training from score -1.131402
[LightGBM] [Info] Start training from score -0.908259
[LightGBM] [Info] Start training from score -1.293921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Learning rate set to 0.071136
0:	learn: 1.0389562	total: 3.73ms	remaining: 3.73s
1:	learn: 0.9847747	total: 7.32ms	remaining: 3.65s
2:	learn: 0.9286253	total: 12.1ms	remaining: 4.03s
3:	learn: 0.8852436	total: 16.5ms	remaining: 4.1s
4:	learn: 0.8353990	total: 20.8ms	remaining: 4.14s
5:	learn: 0.7978601	total: 25.5ms	remaining: 4.23s
6:	learn: 0.7547053	total: 29.8ms	remaining: 4.23s
7:	learn: 0.7240475	total: 34.4ms	remaining: 4.26s
8:	learn: 0.6994660	total: 38.9ms	remaining: 4.28s
9:	learn: 0.6748218	total: 43.2ms	remaining: 4.28s
10:	learn: 0.6469836	total: 47.5ms	remaining: 4.27s
11:	learn: 0.6241805	total: 52.5ms	remaining: 4.32s
12:	learn: 0.5974119	total: 56.7ms	remaining: 4.3s
13:	learn: 0.5741887	total: 60.9ms	remaining: 4.29s
14:	learn: 0.5563143	total: 65ms	remaining: 4.27s
15:	learn: 0.5356108	total: 69.6ms	remaining: 4.28s
16:	learn: 0.5166598	total: 74ms	remaining: 4.28s
17:	learn: 0.4985620	total: 78.4ms	remaining: 4.28s
18:	learn: 0.4831476	total: 83.5ms	remaining: 4.31s
19:	learn: 0.4632679	total: 84.9ms	remaining: 4.16s
20:	learn: 0.4443232	total: 89.3ms	remaining: 4.16s
21:	learn: 0.4283625	total: 93.8ms	remaining: 4.17s
22:	learn: 0.4133013	total: 98.2ms	remaining: 4.17s
23:	learn: 0.3991512	total: 102ms	remaining: 4.15s
24:	learn: 0.3870603	total: 107ms	remaining: 4.16s
25:	learn: 0.3739902	total: 110ms	remaining: 4.12s
26:	learn: 0.3604801	total: 115ms	remaining: 4.13s
27:	learn: 0.3488023	total: 119ms	remaining: 4.12s
28:	learn: 0.3377672	total: 123ms	remaining: 4.13s
29:	learn: 0.3281294	total: 126ms	remaining: 4.07s
30:	learn: 0.3191985	total: 129ms	remaining: 4.02s
31:	learn: 0.3081660	total: 131ms	remaining: 3.97s
32:	learn: 0.3005622	total: 135ms	remaining: 3.97s
33:	learn: 0.2925532	total: 138ms	remaining: 3.93s
34:	learn: 0.2862694	total: 143ms	remaining: 3.94s
35:	learn: 0.2790748	total: 146ms	remaining: 3.92s
36:	learn: 0.2710228	total: 151ms	remaining: 3.92s
37:	learn: 0.2634577	total: 155ms	remaining: 3.92s
38:	learn: 0.2560572	total: 159ms	remaining: 3.92s
39:	learn: 0.2484497	total: 163ms	remaining: 3.92s
40:	learn: 0.2435303	total: 168ms	remaining: 3.92s
41:	learn: 0.2383614	total: 172ms	remaining: 3.92s
42:	learn: 0.2319889	total: 175ms	remaining: 3.9s
43:	learn: 0.2261014	total: 179ms	remaining: 3.89s
44:	learn: 0.2199610	total: 182ms	remaining: 3.87s
45:	learn: 0.2152405	total: 186ms	remaining: 3.85s
46:	learn: 0.2102476	total: 190ms	remaining: 3.85s
47:	learn: 0.2061806	total: 194ms	remaining: 3.85s
48:	learn: 0.2013445	total: 196ms	remaining: 3.81s
49:	learn: 0.1978560	total: 200ms	remaining: 3.8s
50:	learn: 0.1937943	total: 204ms	remaining: 3.79s
51:	learn: 0.1899759	total: 208ms	remaining: 3.79s
52:	learn: 0.1855662	total: 212ms	remaining: 3.78s
53:	learn: 0.1818667	total: 215ms	remaining: 3.77s
54:	learn: 0.1789007	total: 219ms	remaining: 3.76s
55:	learn: 0.1754578	total: 223ms	remaining: 3.77s
56:	learn: 0.1725388	total: 228ms	remaining: 3.77s
57:	learn: 0.1698814	total: 232ms	remaining: 3.77s
58:	learn: 0.1671538	total: 236ms	remaining: 3.77s
59:	learn: 0.1644457	total: 240ms	remaining: 3.77s
60:	learn: 0.1622089	total: 245ms	remaining: 3.77s
61:	learn: 0.1588049	total: 249ms	remaining: 3.77s
62:	learn: 0.1559516	total: 254ms	remaining: 3.77s
63:	learn: 0.1522484	total: 258ms	remaining: 3.77s
64:	learn: 0.1496082	total: 262ms	remaining: 3.77s
65:	learn: 0.1477667	total: 266ms	remaining: 3.77s
66:	learn: 0.1447413	total: 271ms	remaining: 3.77s
67:	learn: 0.1421360	total: 275ms	remaining: 3.76s
68:	learn: 0.1398059	total: 277ms	remaining: 3.74s
69:	learn: 0.1376685	total: 281ms	remaining: 3.73s
70:	learn: 0.1348369	total: 283ms	remaining: 3.7s
71:	learn: 0.1326934	total: 287ms	remaining: 3.7s
72:	learn: 0.1309118	total: 290ms	remaining: 3.68s
73:	learn: 0.1286944	total: 294ms	remaining: 3.68s
74:	learn: 0.1269505	total: 297ms	remaining: 3.67s
75:	learn: 0.1252053	total: 302ms	remaining: 3.67s
76:	learn: 0.1225672	total: 306ms	remaining: 3.67s
77:	learn: 0.1202099	total: 310ms	remaining: 3.66s
78:	learn: 0.1187083	total: 314ms	remaining: 3.66s
79:	learn: 0.1162663	total: 318ms	remaining: 3.66s
80:	learn: 0.1143903	total: 322ms	remaining: 3.66s
81:	learn: 0.1120246	total: 329ms	remaining: 3.68s
82:	learn: 0.1105479	total: 333ms	remaining: 3.68s
83:	learn: 0.1080614	total: 338ms	remaining: 3.69s
84:	learn: 0.1062671	total: 342ms	remaining: 3.68s
85:	learn: 0.1048276	total: 347ms	remaining: 3.69s
86:	learn: 0.1030361	total: 351ms	remaining: 3.69s
87:	learn: 0.1018862	total: 355ms	remaining: 3.68s
88:	learn: 0.1000920	total: 359ms	remaining: 3.68s
89:	learn: 0.0989832	total: 364ms	remaining: 3.68s
90:	learn: 0.0976019	total: 366ms	remaining: 3.66s
91:	learn: 0.0961094	total: 369ms	remaining: 3.65s
92:	learn: 0.0949124	total: 373ms	remaining: 3.64s
93:	learn: 0.0937457	total: 377ms	remaining: 3.64s
94:	learn: 0.0919062	total: 382ms	remaining: 3.63s
95:	learn: 0.0902624	total: 385ms	remaining: 3.62s
96:	learn: 0.0888401	total: 387ms	remaining: 3.6s
97:	learn: 0.0877908	total: 390ms	remaining: 3.59s
98:	learn: 0.0860242	total: 394ms	remaining: 3.58s
99:	learn: 0.0847129	total: 397ms	remaining: 3.57s
100:	learn: 0.0835687	total: 400ms	remaining: 3.56s
101:	learn: 0.0824465	total: 403ms	remaining: 3.55s
102:	learn: 0.0812380	total: 408ms	remaining: 3.55s
103:	learn: 0.0800961	total: 410ms	remaining: 3.53s
104:	learn: 0.0790148	total: 414ms	remaining: 3.53s
105:	learn: 0.0780179	total: 417ms	remaining: 3.51s
106:	learn: 0.0768823	total: 421ms	remaining: 3.51s
107:	learn: 0.0759344	total: 424ms	remaining: 3.5s
108:	learn: 0.0749253	total: 428ms	remaining: 3.5s
109:	learn: 0.0740705	total: 432ms	remaining: 3.49s
110:	learn: 0.0731283	total: 436ms	remaining: 3.49s
111:	learn: 0.0721847	total: 440ms	remaining: 3.49s
112:	learn: 0.0711815	total: 444ms	remaining: 3.49s
113:	learn: 0.0704180	total: 449ms	remaining: 3.49s
114:	learn: 0.0694707	total: 453ms	remaining: 3.49s
115:	learn: 0.0682834	total: 458ms	remaining: 3.49s
116:	learn: 0.0676388	total: 463ms	remaining: 3.49s
117:	learn: 0.0668372	total: 467ms	remaining: 3.49s
118:	learn: 0.0659610	total: 472ms	remaining: 3.49s
119:	learn: 0.0653236	total: 476ms	remaining: 3.49s
120:	learn: 0.0644830	total: 480ms	remaining: 3.49s
121:	learn: 0.0637682	total: 485ms	remaining: 3.49s
122:	learn: 0.0633368	total: 489ms	remaining: 3.49s
123:	learn: 0.0626308	total: 494ms	remaining: 3.49s
124:	learn: 0.0620989	total: 499ms	remaining: 3.49s
125:	learn: 0.0614727	total: 503ms	remaining: 3.49s
126:	learn: 0.0608476	total: 507ms	remaining: 3.49s
127:	learn: 0.0602357	total: 511ms	remaining: 3.48s
128:	learn: 0.0597651	total: 513ms	remaining: 3.46s
129:	learn: 0.0591034	total: 516ms	remaining: 3.46s
130:	learn: 0.0586003	total: 520ms	remaining: 3.45s
131:	learn: 0.0578466	total: 523ms	remaining: 3.44s
132:	learn: 0.0572363	total: 527ms	remaining: 3.43s
133:	learn: 0.0567977	total: 530ms	remaining: 3.42s
134:	learn: 0.0560241	total: 534ms	remaining: 3.42s
135:	learn: 0.0553801	total: 538ms	remaining: 3.42s
136:	learn: 0.0549870	total: 543ms	remaining: 3.42s
137:	learn: 0.0543616	total: 547ms	remaining: 3.42s
138:	learn: 0.0537968	total: 551ms	remaining: 3.42s
139:	learn: 0.0534008	total: 556ms	remaining: 3.41s
140:	learn: 0.0528633	total: 559ms	remaining: 3.41s
141:	learn: 0.0525123	total: 562ms	remaining: 3.39s
142:	learn: 0.0519905	total: 565ms	remaining: 3.38s
143:	learn: 0.0514311	total: 568ms	remaining: 3.37s
144:	learn: 0.0508079	total: 571ms	remaining: 3.36s
145:	learn: 0.0503389	total: 574ms	remaining: 3.35s
146:	learn: 0.0499303	total: 576ms	remaining: 3.34s
147:	learn: 0.0495930	total: 579ms	remaining: 3.33s
148:	learn: 0.0489275	total: 583ms	remaining: 3.33s
149:	learn: 0.0484563	total: 587ms	remaining: 3.32s
150:	learn: 0.0479325	total: 590ms	remaining: 3.32s
151:	learn: 0.0476003	total: 595ms	remaining: 3.32s
152:	learn: 0.0470288	total: 599ms	remaining: 3.31s
153:	learn: 0.0464905	total: 603ms	remaining: 3.31s
154:	learn: 0.0460350	total: 606ms	remaining: 3.3s
155:	learn: 0.0456512	total: 611ms	remaining: 3.3s
156:	learn: 0.0452437	total: 615ms	remaining: 3.3s
157:	learn: 0.0449245	total: 620ms	remaining: 3.3s
158:	learn: 0.0445112	total: 624ms	remaining: 3.3s
159:	learn: 0.0441801	total: 629ms	remaining: 3.3s
160:	learn: 0.0438060	total: 633ms	remaining: 3.3s
161:	learn: 0.0434639	total: 638ms	remaining: 3.3s
162:	learn: 0.0431213	total: 645ms	remaining: 3.31s
163:	learn: 0.0428224	total: 650ms	remaining: 3.31s
164:	learn: 0.0425339	total: 654ms	remaining: 3.31s
165:	learn: 0.0422339	total: 659ms	remaining: 3.31s
166:	learn: 0.0418994	total: 664ms	remaining: 3.31s
167:	learn: 0.0416078	total: 669ms	remaining: 3.31s
168:	learn: 0.0412259	total: 674ms	remaining: 3.31s
169:	learn: 0.0409438	total: 678ms	remaining: 3.31s
170:	learn: 0.0406670	total: 683ms	remaining: 3.31s
171:	learn: 0.0403269	total: 687ms	remaining: 3.31s
172:	learn: 0.0401068	total: 691ms	remaining: 3.3s
173:	learn: 0.0398496	total: 696ms	remaining: 3.3s
174:	learn: 0.0394537	total: 700ms	remaining: 3.3s
175:	learn: 0.0390318	total: 705ms	remaining: 3.3s
176:	learn: 0.0388312	total: 709ms	remaining: 3.3s
177:	learn: 0.0385295	total: 713ms	remaining: 3.29s
178:	learn: 0.0382745	total: 716ms	remaining: 3.29s
179:	learn: 0.0378568	total: 720ms	remaining: 3.28s
180:	learn: 0.0376083	total: 723ms	remaining: 3.27s
181:	learn: 0.0372802	total: 726ms	remaining: 3.26s
182:	learn: 0.0370114	total: 729ms	remaining: 3.25s
183:	learn: 0.0366935	total: 734ms	remaining: 3.25s
184:	learn: 0.0363276	total: 737ms	remaining: 3.25s
185:	learn: 0.0360832	total: 741ms	remaining: 3.24s
186:	learn: 0.0358505	total: 745ms	remaining: 3.24s
187:	learn: 0.0356657	total: 750ms	remaining: 3.24s
188:	learn: 0.0354342	total: 754ms	remaining: 3.23s
189:	learn: 0.0351960	total: 760ms	remaining: 3.24s
190:	learn: 0.0349790	total: 764ms	remaining: 3.23s
191:	learn: 0.0346805	total: 766ms	remaining: 3.23s
192:	learn: 0.0344879	total: 769ms	remaining: 3.21s
193:	learn: 0.0341659	total: 771ms	remaining: 3.2s
194:	learn: 0.0339999	total: 774ms	remaining: 3.19s
195:	learn: 0.0337231	total: 778ms	remaining: 3.19s
196:	learn: 0.0336575	total: 781ms	remaining: 3.18s
197:	learn: 0.0333663	total: 785ms	remaining: 3.18s
198:	learn: 0.0331427	total: 788ms	remaining: 3.17s
199:	learn: 0.0329116	total: 792ms	remaining: 3.17s
200:	learn: 0.0326881	total: 796ms	remaining: 3.16s
201:	learn: 0.0324300	total: 800ms	remaining: 3.16s
202:	learn: 0.0322646	total: 804ms	remaining: 3.16s
203:	learn: 0.0320644	total: 809ms	remaining: 3.15s
204:	learn: 0.0318905	total: 813ms	remaining: 3.15s
205:	learn: 0.0316681	total: 817ms	remaining: 3.15s
206:	learn: 0.0314286	total: 822ms	remaining: 3.15s
207:	learn: 0.0312293	total: 826ms	remaining: 3.15s
208:	learn: 0.0310871	total: 831ms	remaining: 3.15s
209:	learn: 0.0309312	total: 836ms	remaining: 3.14s
210:	learn: 0.0307604	total: 840ms	remaining: 3.14s
211:	learn: 0.0304470	total: 844ms	remaining: 3.14s
212:	learn: 0.0302893	total: 849ms	remaining: 3.14s
213:	learn: 0.0300849	total: 853ms	remaining: 3.13s
214:	learn: 0.0298566	total: 858ms	remaining: 3.13s
215:	learn: 0.0296842	total: 862ms	remaining: 3.13s
216:	learn: 0.0295433	total: 867ms	remaining: 3.13s
217:	learn: 0.0292965	total: 870ms	remaining: 3.12s
218:	learn: 0.0291203	total: 873ms	remaining: 3.11s
219:	learn: 0.0289739	total: 875ms	remaining: 3.1s
220:	learn: 0.0288488	total: 879ms	remaining: 3.1s
221:	learn: 0.0286887	total: 882ms	remaining: 3.09s
222:	learn: 0.0285767	total: 885ms	remaining: 3.08s
223:	learn: 0.0284593	total: 888ms	remaining: 3.08s
224:	learn: 0.0282708	total: 893ms	remaining: 3.08s
225:	learn: 0.0281024	total: 897ms	remaining: 3.07s
226:	learn: 0.0279078	total: 901ms	remaining: 3.07s
227:	learn: 0.0276788	total: 905ms	remaining: 3.06s
228:	learn: 0.0274987	total: 908ms	remaining: 3.06s
229:	learn: 0.0273593	total: 912ms	remaining: 3.05s
230:	learn: 0.0271539	total: 917ms	remaining: 3.05s
231:	learn: 0.0270396	total: 921ms	remaining: 3.05s
232:	learn: 0.0269281	total: 925ms	remaining: 3.05s
233:	learn: 0.0267330	total: 930ms	remaining: 3.04s
234:	learn: 0.0265874	total: 934ms	remaining: 3.04s
235:	learn: 0.0264098	total: 939ms	remaining: 3.04s
236:	learn: 0.0263093	total: 943ms	remaining: 3.04s
237:	learn: 0.0261992	total: 947ms	remaining: 3.03s
238:	learn: 0.0260829	total: 951ms	remaining: 3.03s
239:	learn: 0.0259687	total: 956ms	remaining: 3.02s
240:	learn: 0.0257809	total: 960ms	remaining: 3.02s
241:	learn: 0.0256780	total: 965ms	remaining: 3.02s
242:	learn: 0.0255844	total: 968ms	remaining: 3.02s
243:	learn: 0.0254586	total: 972ms	remaining: 3.01s
244:	learn: 0.0253566	total: 974ms	remaining: 3s
245:	learn: 0.0252165	total: 977ms	remaining: 2.99s
246:	learn: 0.0250930	total: 980ms	remaining: 2.99s
247:	learn: 0.0249219	total: 983ms	remaining: 2.98s
248:	learn: 0.0247445	total: 987ms	remaining: 2.98s
249:	learn: 0.0246034	total: 991ms	remaining: 2.97s
250:	learn: 0.0244561	total: 995ms	remaining: 2.97s
251:	learn: 0.0243305	total: 999ms	remaining: 2.96s
252:	learn: 0.0241933	total: 1s	remaining: 2.96s
253:	learn: 0.0241057	total: 1.01s	remaining: 2.96s
254:	learn: 0.0239827	total: 1.01s	remaining: 2.96s
255:	learn: 0.0238746	total: 1.02s	remaining: 2.95s
256:	learn: 0.0237769	total: 1.02s	remaining: 2.95s
257:	learn: 0.0236948	total: 1.02s	remaining: 2.95s
258:	learn: 0.0235833	total: 1.03s	remaining: 2.94s
259:	learn: 0.0234928	total: 1.03s	remaining: 2.94s
260:	learn: 0.0234158	total: 1.04s	remaining: 2.93s
261:	learn: 0.0232420	total: 1.04s	remaining: 2.93s
262:	learn: 0.0230742	total: 1.04s	remaining: 2.92s
263:	learn: 0.0229634	total: 1.05s	remaining: 2.92s
264:	learn: 0.0228482	total: 1.05s	remaining: 2.91s
265:	learn: 0.0227373	total: 1.05s	remaining: 2.91s
266:	learn: 0.0226348	total: 1.06s	remaining: 2.9s
267:	learn: 0.0225361	total: 1.06s	remaining: 2.9s
268:	learn: 0.0223876	total: 1.07s	remaining: 2.9s
269:	learn: 0.0222764	total: 1.07s	remaining: 2.89s
270:	learn: 0.0221512	total: 1.07s	remaining: 2.89s
271:	learn: 0.0220308	total: 1.08s	remaining: 2.89s
272:	learn: 0.0219440	total: 1.08s	remaining: 2.89s
273:	learn: 0.0218484	total: 1.09s	remaining: 2.88s
274:	learn: 0.0217762	total: 1.09s	remaining: 2.88s
275:	learn: 0.0216835	total: 1.1s	remaining: 2.88s
276:	learn: 0.0215707	total: 1.1s	remaining: 2.88s
277:	learn: 0.0214467	total: 1.11s	remaining: 2.87s
278:	learn: 0.0213573	total: 1.11s	remaining: 2.87s
279:	learn: 0.0212751	total: 1.12s	remaining: 2.87s
280:	learn: 0.0211904	total: 1.12s	remaining: 2.87s
281:	learn: 0.0211092	total: 1.13s	remaining: 2.86s
282:	learn: 0.0210420	total: 1.13s	remaining: 2.86s
283:	learn: 0.0209355	total: 1.13s	remaining: 2.86s
284:	learn: 0.0208745	total: 1.14s	remaining: 2.85s
285:	learn: 0.0207919	total: 1.14s	remaining: 2.85s
286:	learn: 0.0207103	total: 1.15s	remaining: 2.85s
287:	learn: 0.0206050	total: 1.15s	remaining: 2.85s
288:	learn: 0.0204731	total: 1.16s	remaining: 2.84s
289:	learn: 0.0203798	total: 1.16s	remaining: 2.84s
290:	learn: 0.0202527	total: 1.16s	remaining: 2.83s
291:	learn: 0.0201401	total: 1.16s	remaining: 2.82s
292:	learn: 0.0200279	total: 1.17s	remaining: 2.82s
293:	learn: 0.0199488	total: 1.17s	remaining: 2.81s
294:	learn: 0.0198652	total: 1.17s	remaining: 2.81s
295:	learn: 0.0197767	total: 1.18s	remaining: 2.8s
296:	learn: 0.0196649	total: 1.18s	remaining: 2.8s
297:	learn: 0.0195819	total: 1.19s	remaining: 2.79s
298:	learn: 0.0195133	total: 1.19s	remaining: 2.79s
299:	learn: 0.0194129	total: 1.19s	remaining: 2.79s
300:	learn: 0.0193446	total: 1.2s	remaining: 2.78s
301:	learn: 0.0192776	total: 1.2s	remaining: 2.78s
302:	learn: 0.0191799	total: 1.21s	remaining: 2.77s
303:	learn: 0.0191094	total: 1.21s	remaining: 2.77s
304:	learn: 0.0190529	total: 1.21s	remaining: 2.77s
305:	learn: 0.0189956	total: 1.22s	remaining: 2.76s
306:	learn: 0.0189299	total: 1.22s	remaining: 2.76s
307:	learn: 0.0188530	total: 1.23s	remaining: 2.76s
308:	learn: 0.0187656	total: 1.23s	remaining: 2.75s
309:	learn: 0.0186885	total: 1.24s	remaining: 2.75s
310:	learn: 0.0186341	total: 1.24s	remaining: 2.75s
311:	learn: 0.0185465	total: 1.25s	remaining: 2.75s
312:	learn: 0.0184581	total: 1.25s	remaining: 2.74s
313:	learn: 0.0183915	total: 1.25s	remaining: 2.74s
314:	learn: 0.0183103	total: 1.26s	remaining: 2.74s
315:	learn: 0.0182554	total: 1.26s	remaining: 2.73s
316:	learn: 0.0181978	total: 1.27s	remaining: 2.73s
317:	learn: 0.0181468	total: 1.27s	remaining: 2.73s
318:	learn: 0.0180889	total: 1.28s	remaining: 2.73s
319:	learn: 0.0180374	total: 1.28s	remaining: 2.73s
320:	learn: 0.0179365	total: 1.29s	remaining: 2.72s
321:	learn: 0.0178501	total: 1.29s	remaining: 2.72s
322:	learn: 0.0177902	total: 1.3s	remaining: 2.72s
323:	learn: 0.0177310	total: 1.3s	remaining: 2.71s
324:	learn: 0.0176839	total: 1.3s	remaining: 2.71s

In [38]:
#collect all models collecion : 
models=[
    {'name':'AdaBoost','model':model_adaboost},
    {'name':'Gredient','model':model_gredient_boost},
    {'name':'XGBoost','model':model_xgb},
    {'name':'Light_boost','model':model_light_gbm},
    {'name':'Cat Boost','model':model_cat_boost}
]

In [39]:
evaluation_metrics=[]
for info in models:
    evaluation_metrics.append(evaluate_model(info['model'],info['name'],x_train,y_train))

pd.DataFrame(evaluation_metrics,columns=['MOdelName','Accuracy','Precision','F1','Recall'])

     MOdelName  Accuracy  Precision        F1    Recall
0     AdaBoost  1.000000   1.000000  1.000000  1.000000
1     Gredient  1.000000   1.000000  1.000000  1.000000
2      XGBoost  1.000000   1.000000  1.000000  1.000000
3  Light_boost  0.983871   0.983871  0.983871  0.983871
4    Cat Boost  1.000000   1.000000  1.000000  1.000000

In [40]:
evaluation_metrics=[]
for info in models:
    evaluation_metrics.append(evaluate_model(info['model'],info['name'],x_test,y_test))

pd.DataFrame(evaluation_metrics,columns=['MOdelName','Accuracy','Precision','F1','Recall'])

     MOdelName  Accuracy  Precision        F1    Recall
0     AdaBoost  0.944444   0.944444  0.944444  0.944444
1     Gredient  0.925926   0.925926  0.925926  0.925926
2      XGBoost  0.944444   0.944444  0.944444  0.944444
3  Light_boost  0.944444   0.944444  0.944444  0.944444
4    Cat Boost  0.962963   0.962963  0.962963  0.962963