In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("globalAirQuality.csv")

In [5]:
#Filter the data
df[df["aqi"]>100]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [7]:
df[(df["aqi"]>100) & (df["country"]=="US")]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16195,2025-11-19 13:25:17.554219,US,Houston,29.760,-95.370,40.233,87.646,41.984,9.013,45.678,0.149,104,22.672,72.953,0.706
16196,2025-11-19 14:25:17.554219,US,Houston,29.760,-95.370,52.887,99.892,28.703,4.214,35.680,0.654,105,12.411,31.414,9.917
16197,2025-11-19 15:25:17.554219,US,Houston,29.760,-95.370,61.548,101.721,12.324,2.901,39.892,0.697,123,8.683,68.281,5.345
16198,2025-11-19 16:25:17.554219,US,Houston,29.760,-95.370,51.005,57.365,14.859,6.705,35.555,0.783,102,16.854,62.782,5.717
16199,2025-11-19 17:25:17.554219,US,Houston,29.760,-95.370,56.126,57.432,30.305,6.860,51.699,0.516,112,22.639,60.386,8.294

In [18]:
df[df["aqi"]>100][["city","aqi"]]
aqi_data=df[(df["aqi"]>100) & (df["country"]=="US")][["city","aqi"]]
aqi_data
aqi_data.loc[0]
aqi_data.iloc[2]

city    New York
aqi          155
Name: 6, dtype: object

In [25]:
#Query : by default copy()
aqi_data=150
df.query("aqi> @aqi_data & country=='US' ")[["city","aqi"]].copy()

           city  aqi
3      New York  158
6      New York  155
19     New York  151
44     New York  156
53     New York  153
...         ...  ...
16039   Houston  151
16055   Houston  187
16080   Houston  156
16101   Houston  175
16149   Houston  155

[89 rows x 2 columns]